### ISSUE TITLE
Spaces not supported for sandbox on mac

### ISSUE THREAD

**Issue by sigdestad** [enonic/cli-enonic#127]
At least on macs, spaces are not working properly for sandboxes.
Apparently, sandbox is created fine, but XP_HOME is set incorrectly?

See screenshot below:
![Screenshot 2019-04-25 at 12 44 48](https://user-images.githubusercontent.com/482228/56730373-265e2d80-6758-11e9-95a8-ae92ad7ec8eb.png)

Fix and verify on both Mac and Windows..

**Comment by alansemenov** [comment]
@pmi We need to test this fix against the latest version (RC5), since @GlennRicaud made a fix there for the same issue:
https://github.com/enonic/xp/commit/dbff18563b657f4314e9c467d5b9d042a6b05a38
https://github.com/enonic/xp/commit/32b5a365b0d4cac549e54c22bcbda745c63060dc#diff-3c7c0306a3da9948deaa140a9274d320

The question is if we need both fixes (CLI and XP).

**Comment by sigdestad** [comment]
I can confirm that this is now working fine on Mac using CLI 1.0.4.
So, we should not make any changes to CLI I assume?
Have you guys verified this on windows and Linux?
