### ISSUE TITLE
Check for new version of cli

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#138]
I have discovered the cli tool might become outdated quite quickly.

Getting into a habit of running
```brew upgrade enonic```
seems like a lot to ask?

So perhaps only running

```
enonic
```

Or on every help screen.

The cli could go online and check for new versions.
Or perhaps only once a day.

**Comment by alansemenov** [comment]
This is a good idea. We can check for the last version, compare it with current and output a text line at the top (in some special color) saying "New version {x.y} is available. Run "brew upgrade enonic" to upgrade your local CLI"

**Comment by pmi** [comment]
There's no way to do a background version check without holding the main thread and making user wait with every request is not a good idea.

So I  created an `enonic latest` command that checks for the latest version and stores it along with a check time.

Every time you run `enonic` (can be on every command as well) it checks stored values whether there is a newer version as well as time passed since last check ( 30 days is the threshold ) and shows corresponding messages.
