### ISSUE TITLE
Could not parse toml file:  read .enonic: is a directory

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#140]
Running enonic sandbox start in the $HOME folder fails:

```bash
$ enonic sandbox start
Could not parse toml file:  read .enonic: is a directory
```

**Comment by alansemenov** [comment]
@sigdestad  Should we consider giving the project file and the folder with sandboxes two different names? Now both are called ".enonic", but one is a file and another is a folder.

**Comment by sigdestad** [comment]
The sandbox file should be called.. .running or something like that I assume? Or is there a file inside the sandbox as well?

**Comment by alansemenov** [comment]
@pmi Caused by https://github.com/enonic/cli-enonic/issues/136

If you run `enonic sandbox start` in the root (where `.enonic` folder is), then CLI tries to read from `.enonic` file in the current folder to determine which sandbox to start and fails because ".enonic" is a folder, not a file. 

We have to check whether ".enonic" is a folder or a file before attempting to read from it. If there's no **file** called `.enonic` in the current folder, then give the list of sandboxes to choose from.
