### ISSUE TITLE
Show example of a custom repo path in project create wizard

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#151]
When using a custom repo, there is no example of what to input.
So I first tried using what git remote -v prints out.

In the next attempt I tried removing the scheme and domain. (In other words we only support github).
But I had to CTRL+C because I could not use the folder the previous command had created.

From the third attempt I learned I had to remove the extention too.

So fourth try success.

This can be much improved.

```
$ enonic project create

Loading starters from enonic market...Done.
? Starter Custom repo
? Custom repository git@github.com:enonic/starter-explorer-collector.git
? Project name com.enonic.app.explorer.collector.domain
? Destination folder app-explorer-collector-domain
? Project version 1.0.0-SNAPSHOT

Initializing project...
Could not connect to a remote repository 'https://github.com/git@github.com:enonic/starter-explorer-collector.git.git unexpected client error: unexpected requesting "https://github.com/git@github.com:enonic/starter-explorer-collector.git.git/info/refs?service=git-upload-pack" status code: 400

$ enonic project create

Loading starters from enonic market...Done.
? Starter Custom repo
? Custom repository enonic/starter-explorer-collector.git
? Project name com.enonic.app.explorer.collector.domain
>> Destination folder 'app-explorer-collector-domain' already exists:

$ rm -r app-explorer-collector-domain

$ enonic project create

Loading starters from enonic market...Done.
? Starter Custom repo
? Custom repository enonic/starter-explorer-collector.git
? Project name com.enonic.app.explorer.collector.domain
? Destination folder app-explorer-collector-domain
? Project version 1.0.0-SNAPSHOT

Initializing project...
Could not connect to a remote repository 'https://github.com/enonic/starter-explorer-collector.git.git authentication required

$ enonic project create

Loading starters from enonic market...Done.
? Starter Custom repo
? Custom repository enonic/starter-explorer-collector
? Project name com.enonic.app.explorer.collector.domain
? Destination folder app-explorer-collector-domain
? Project version 1.0.0-SNAPSHOT

Initializing project...
Enumerating objects: 56, done.
Counting objects: 100% (56/56), done.
Compressing objects: 100% (31/31), done.
Total 56 (delta 10), reused 54 (delta 8), pack-reused 0

? A sandbox is required for your project, select one: fhi-qa ( mac-sdk-7.0.2-RC1 )

Project created in '/Users/.../app-explorer-collector-domain' and linked to 'sandboxname'
```

**Comment by alansemenov** [comment]
@pmi Let's show input example in the brackets when asking for repo path, like we do for a project name `Project name (com.example.myproject)` 

I also think that we should change `Custom repository` to `Custom Github repository`.

Now:
![image](https://user-images.githubusercontent.com/11612490/60160025-bff79900-97f4-11e9-8710-2abf9eb24acc.png)

Change the last line to:
`Custom Github repository (account/repository)` (value in brackets should be in grey color)

I also suggest that we simply remove `.git` in the end if user inputs it (like in `enonic/starter-explorer-collector.git`) - there's no reason to fail the wizard only because of that.

**Comment by sigdestad** [comment]
We should not say "github", but "Git" maybe?

**Comment by pmi** [comment]
@alansemenov I'm afraid I can't add repo example like in _Project name (com.example.myproject)_ because text in braces is actually the default value that is applied on enter and I don't see any suitable default value for custom git url.

But I modified the url guessing algorithm so that it doesn't fail because of **.git** suffix, and does url parsing to verify it integrity.
All the same is applied to --repo param.

Also with --help command working now, the custom url example can be seen there.

**Comment by sigdestad** [comment]
+1
