### ISSUE TITLE
enonic project create project name cmdline parameter

### ISSUE THREAD

**Issue by ComLock** [enonic/cli-enonic#161]
If you do:

```bash
enonic project create -r enonic/starter-explorer-client -d mySearchClient
```

You will be promted with

```bash
? Project name (com.example.myproject)
```

Please make it possible to set project name as a cmdline parameter.

**Comment by alansemenov** [comment]
It should also describe supported flags (like `-r`) when calling `enonic project create -h`. Now it simply says _Create new project_ which is not much of a help.

![image](https://user-images.githubusercontent.com/11612490/61456987-acf56600-a967-11e9-856c-ea3f35bffb06.png)

**Comment by pmi** [comment]
According to CLI docs there always has been a way to specify name using first argument following `enonic project create`, e.g `enonic project create my.cool.project`

`enonic project create -h` has been fixed by now, but it still doesn't document arguments and there's no way to know that there is a `name` argument, so I added the `--name` flag as well.

Updated docs to say that there are 2 ways to specify project name now:
https://developer.enonic.com/docs/enonic-cli/master#create_2
